// <auto-generated />
namespace ProductManagementSystem_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class addDispositionAndPriority : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDispositionAndPriority));
        
        string IMigrationMetadata.Id
        {
            get { return "202607281038547_addDispositionAndPriority"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
